export const COUNTRIES = [
  ["AD", "Andorra"],
  ["AE", "UAE / Vereinigte Arabische Emirate"],
  ["AF", "Afghanistan"],
  ["AG", "Antigua & Barbuda"],
  ["AL", "Albania / Albanien"],
  ["AM", "Armenia / Armenien"],
  ["AO", "Angola"],
  ["AR", "Argentina / Argentinien"],
  ["AT", "Austria / Österreich"],
  ["AU", "Australia / Australien"],
  ["AZ", "Azerbaijan / Aserbaidschan"],
  ["BA", "Bosnia / Bosnien"],
  ["BB", "Barbados"],
  ["BD", "Bangladesh"],
  ["BE", "Belgium / Belgien"],
  ["BF", "Burkina Faso"],
  ["BG", "Bulgaria / Bulgarien"],
  ["BH", "Bahrain"],
  ["BI", "Burundi"],
  ["BJ", "Benin"],
  ["BM", "Bermuda"],
  ["BN", "Brunei"],
  ["BO", "Bolivia / Bolivien"],
  ["BR", "Brazil / Brasilien"],
  ["BS", "Bahamas"],
  ["BT", "Bhutan"],
  ["BW", "Botswana"],
  ["BY", "Belarus"],
  ["BZ", "Belize"],
  ["CA", "Canada / Kanada"],
  ["CD", "DR Congo / DR Kongo"],
  ["CF", "Central African Rep."],
  ["CG", "Republic of Congo"],
  ["CH", "Switzerland / Schweiz"],
  ["CI", "Côte d'Ivoire"],
  ["CL", "Chile"],
  ["CM", "Cameroon / Kamerun"],
  ["CN", "China"],
  ["CO", "Colombia / Kolumbien"],
  ["CR", "Costa Rica"],
  ["CU", "Cuba / Kuba"],
  ["CV", "Cape Verde / Kap Verde"],
  ["CW", "Curaçao"],
  ["CY", "Cyprus / Zypern"],
  ["CZ", "Czech Republic / Tschechien"],
  ["DE", "Germany / Deutschland"],
  ["DJ", "Djibouti"],
  ["DK", "Denmark / Dänemark"],
  ["DM", "Dominica"],
  ["DO", "Dominican Republic"],
  ["DZ", "Algeria / Algerien"],
  ["EC", "Ecuador"],
  ["EE", "Estonia / Estland"],
  ["EG", "Egypt / Ägypten"],
  ["ER", "Eritrea"],
  ["ES", "Spain / Spanien"],
  ["ET", "Ethiopia / Äthiopien"],
  ["FI", "Finland / Finnland"],
  ["FJ", "Fiji"],
  ["FR", "France / Frankreich"],
  ["GA", "Gabon / Gabun"],
  ["GB", "United Kingdom / Großbritannien"],
  ["GD", "Grenada"],
  ["GE", "Georgia / Georgien"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GL", "Greenland / Grönland"],
  ["GM", "Gambia"],
  ["GN", "Guinea"],
  ["GQ", "Equatorial Guinea"],
  ["GR", "Greece / Griechenland"],
  ["GT", "Guatemala"],
  ["GW", "Guinea-Bissau"],
  ["GY", "Guyana"],
  ["HK", "Hong Kong / Hongkong"],
  ["HN", "Honduras"],
  ["HR", "Croatia / Kroatien"],
  ["HT", "Haiti"],
  ["HU", "Hungary / Ungarn"],
  ["ID", "Indonesia / Indonesien"],
  ["IE", "Ireland / Irland"],
  ["IL", "Israel"],
  ["IN", "India / Indien"],
  ["IQ", "Iraq / Irak"],
  ["IR", "Iran"],
  ["IS", "Iceland / Island"],
  ["IT", "Italy / Italien"],
  ["JM", "Jamaica / Jamaika"],
  ["JO", "Jordan / Jordanien"],
  ["JP", "Japan"],
  ["KE", "Kenya / Kenia"],
  ["KG", "Kyrgyzstan / Kirgisistan"],
  ["KH", "Cambodia / Kambodscha"],
  ["KP", "North Korea / Nordkorea"],
  ["KR", "South Korea / Südkorea"],
  ["KW", "Kuwait"],
  ["KY", "Cayman Islands"],
  ["KZ", "Kazakhstan / Kasachstan"],
  ["LA", "Laos"],
  ["LB", "Lebanon / Libanon"],
  ["LC", "Saint Lucia"],
  ["LI", "Liechtenstein"],
  ["LK", "Sri Lanka"],
  ["LR", "Liberia"],
  ["LS", "Lesotho"],
  ["LT", "Lithuania / Litauen"],
  ["LU", "Luxembourg / Luxemburg"],
  ["LV", "Latvia / Lettland"],
  ["LY", "Libya / Libyen"],
  ["MA", "Morocco / Marokko"],
  ["MC", "Monaco"],
  ["MD", "Moldova / Moldau"],
  ["ME", "Montenegro"],
  ["MG", "Madagascar / Madagaskar"],
  ["MK", "North Macedonia / Nordmazedonien"],
  ["ML", "Mali"],
  ["MM", "Myanmar"],
  ["MN", "Mongolia / Mongolei"],
  ["MO", "Macao"],
  ["MR", "Mauritania / Mauretanien"],
  ["MT", "Malta"],
  ["MU", "Mauritius"],
  ["MV", "Maldives / Malediven"],
  ["MW", "Malawi"],
  ["MX", "Mexico / Mexiko"],
  ["MY", "Malaysia"],
  ["MZ", "Mozambique / Mosambik"],
  ["NA", "Namibia"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["NI", "Nicaragua"],
  ["NL", "Netherlands / Niederlande"],
  ["NO", "Norway / Norwegen"],
  ["NP", "Nepal"],
  ["NZ", "New Zealand / Neuseeland"],
  ["OM", "Oman"],
  ["PA", "Panama"],
  ["PE", "Peru"],
  ["PG", "Papua New Guinea"],
  ["PH", "Philippines / Philippinen"],
  ["PK", "Pakistan"],
  ["PL", "Poland / Polen"],
  ["PS", "Palestinian Territories"],
  ["PT", "Portugal"],
  ["PY", "Paraguay"],
  ["QA", "Qatar / Katar"],
  ["RO", "Romania / Rumänien"],
  ["RS", "Serbia / Serbien"],
  ["RU", "Russia / Russland"],
  ["RW", "Rwanda / Ruanda"],
  ["SA", "Saudi Arabia / Saudi-Arabien"],
  ["SC", "Seychelles / Seychellen"],
  ["SD", "Sudan"],
  ["SE", "Sweden / Schweden"],
  ["SG", "Singapore / Singapur"],
  ["SI", "Slovenia / Slowenien"],
  ["SK", "Slovakia / Slowakei"],
  ["SL", "Sierra Leone"],
  ["SM", "San Marino"],
  ["SN", "Senegal"],
  ["SO", "Somalia"],
  ["SR", "Suriname"],
  ["SS", "South Sudan / Südsudan"],
  ["SV", "El Salvador"],
  ["SY", "Syria / Syrien"],
  ["SZ", "Eswatini"],
  ["TD", "Chad / Tschad"],
  ["TG", "Togo"],
  ["TH", "Thailand"],
  ["TJ", "Tajikistan / Tadschikistan"],
  ["TL", "Timor-Leste"],
  ["TM", "Turkmenistan"],
  ["TN", "Tunisia / Tunesien"],
  ["TO", "Tonga"],
  ["TR", "Turkey / Türkei"],
  ["TT", "Trinidad & Tobago"],
  ["TW", "Taiwan"],
  ["TZ", "Tanzania / Tansania"],
  ["UA", "Ukraine"],
  ["UG", "Uganda"],
  ["US", "United States / USA"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan / Usbekistan"],
  ["VA", "Vatican / Vatikan"],
  ["VE", "Venezuela"],
  ["VN", "Vietnam"],
  ["VU", "Vanuatu"],
  ["WS", "Samoa"],
  ["YE", "Yemen / Jemen"],
  ["ZA", "South Africa / Südafrika"],
  ["ZM", "Zambia / Sambia"],
  ["ZW", "Zimbabwe / Simbabwe"]
].map(([code, name]) => ({ code, name }));

export const CMAP = Object.fromEntries(COUNTRIES.map(c => [c.code, c.name]));
